projectName: "simple-hello-world"
applicationName: "simple-hello-world"
dockerImageName: "simple-hello-world-service"
containerPort: 9050
artifactoryPath: "simple-hello-world"
gitlabPath: "wma/eb/simple-hello-world"
gitRepoUrl: "https://github.com/usgs/simple-hello-world"
gitRepoCredentialsId: "CIDA-Jenkins-GitHub"
